### ISSUE TITLE
React componnent

### ISSUE THREAD

**Issue by Miros-iStore** [georapbox/barcode-scanner#25]
Is there one that is compatible with React?

**Comment by georapbox** [comment]
Hi @Miros-iStore ,

The barcode-scanner is a standalone web application and is not intended to be integrated into other projects. It works independently as a complete solution.

If you're specifically looking for a React-compatible barcode scanning library, there are a few options available in the ecosystem, though I haven't personally explored or used them.

- [React QR Barcode Scanner](https://github.com/jamenamcinteer/react-qr-barcode-scanner) - Uses [@zxing/library](https://github.com/zxing-js/library) under the hood, supporting various formats, not only QR codes as its name implies.
- [React Barcode Scanner](https://github.com/preflower/react-barcode-scanner) - Can be used with any supported barcode formats, based on the [BarcodeDetector API](https://developer.mozilla.org/en-US/docs/Web/API/BarcodeDetector).
